// Code generated by mockery v2. No need to edit manually.
package mocks

import (
	"context"

	"merchant-transactions-api/internal/domain"

	"github.com/stretchr/testify/mock"
)

type TransactionRepository struct {
	mock.Mock
}

func (_m *TransactionRepository) SaveTransaction(ctx context.Context, transaction domain.Transaction) error {
	ret := _m.Called(ctx, transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *TransactionRepository) GetTransaction(ctx context.Context, id string) (*domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			switch v := ret.Get(0).(type) {
			case *domain.Transaction:
				r0 = v
			case domain.Transaction:
				tmp := v
				r0 = &tmp
			}
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *TransactionRepository) ListTransactions(ctx context.Context) ([]domain.Transaction, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Transaction
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *TransactionRepository) DeleteTransaction(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type ReceivableRepository struct {
	mock.Mock
}

func (_m *ReceivableRepository) SaveReceivable(ctx context.Context, receivable domain.Receivable) error {
	ret := _m.Called(ctx, receivable)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Receivable) error); ok {
		r0 = rf(ctx, receivable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *ReceivableRepository) GetReceivable(ctx context.Context, id string) (*domain.Receivable, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Receivable
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Receivable); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			switch v := ret.Get(0).(type) {
			case *domain.Receivable:
				r0 = v
			case domain.Receivable:
				tmp := v
				r0 = &tmp
			}
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *ReceivableRepository) ListReceivables(ctx context.Context) ([]domain.Receivable, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Receivable
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Receivable); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Receivable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *ReceivableRepository) DeleteReceivable(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type Numerator struct {
	mock.Mock
}

func (_m *Numerator) NextID(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
